version: "2"
services:


  target:
    build: target
#    env_file: .env
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - front
    tty: true


  master:
    container_name: ansible_master
#    env_file: .env
    build: master
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - front
    tty: true

networks:
  front:
    driver: bridge
